@startuml
allow_mixing

  namespace tdt4145.core {
      class tdt4145.core.model.Course {
          + courseID : int
          + name : String
          + Course()
          + getCourseID()
          + getName()
      }
    }


    namespace tdt4145.core {
      abstract class tdt4145.core.DBConn {
          # connection : Connection
          + DBConn()
          + connect()
      }
    }


    namespace tdt4145.core {
      class tdt4145.core.repo.Database {
          {static} - DATABASE_DRIVER : String
          {static} - DATABASE_PASSWORD : String
          {static} - DATABASE_URL : String
          {static} - DATABASE_USERNAME : String
          {static} - comboPooledDataSource : ComboPooledDataSource
          {static} - database : Database
          + getConnection()
          {static} + getInstance()
          {static} + setNewDatabase()
          {static} + setNewDatabase()
          - Database()
      }
    }


    namespace tdt4145.core {
      class tdt4145.core.model.Tag {
          - label : String
          - tagID : int
          + Tag()
          + getLabel()
          + getTagID()
      }
    }


    namespace tdt4145.core {
      class tdt4145.core.model.UserOverview {
          - name : String
          - nbpost : int
          - nbreadposts : int
          + UserOverview()
          + getName()
          + getNbpost()
          + getNbreadposts()
          + toString()
      }
    }

  namespace tdt4145.core {
        component DAOs
    }
@enduml
